<a href="https://colab.research.google.com/github/Kaushal-Top5699/tensorflow_07/blob/main/tensorflow_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# **One-Hot Encoding**
Somthing that looks like an identity matrix.

In [2]:
# Creating a simple list.
sample = [0, 1, 2, 3]
# Red, Green, Blue, Orange

In [12]:
# One hot encoding. Note that depth argument is very important, because that defines the size of the resulting matrix or tensor, the identity matrix which we get at the end.
print(f'One-Hot Encoding \n {tf.one_hot(sample, depth=4)}')
# The value of depth will depend on the number of elements in the list.

One-Hot Encoding 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
# What if we change the depth argument
tf.one_hot(sample, depth=5), tf.one_hot(sample, depth=3)

(<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.]], dtype=float32)>)

In [10]:
# Adding custome values to one-hot encoding.
tf.one_hot(sample, depth=4, on_value='K', off_value='T')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'K', b'T', b'T', b'T'],
       [b'T', b'K', b'T', b'T'],
       [b'T', b'T', b'K', b'T'],
       [b'T', b'T', b'T', b'K']], dtype=object)>